// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: server.proto

package employmentService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmploymentCenterClient is the client API for EmploymentCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmploymentCenterClient interface {
	RegisterCompany(ctx context.Context, in *CompanyRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	RegisterEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	CreateNewDepartment(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	EmployPerson(ctx context.Context, in *EmploymentRequest, opts ...grpc.CallOption) (*BasicResponse, error)
}

type employmentCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewEmploymentCenterClient(cc grpc.ClientConnInterface) EmploymentCenterClient {
	return &employmentCenterClient{cc}
}

func (c *employmentCenterClient) RegisterCompany(ctx context.Context, in *CompanyRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/EmploymentCenter/RegisterCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employmentCenterClient) RegisterEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/EmploymentCenter/RegisterEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employmentCenterClient) CreateNewDepartment(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/EmploymentCenter/CreateNewDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employmentCenterClient) EmployPerson(ctx context.Context, in *EmploymentRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/EmploymentCenter/EmployPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmploymentCenterServer is the server API for EmploymentCenter service.
// All implementations should embed UnimplementedEmploymentCenterServer
// for forward compatibility
type EmploymentCenterServer interface {
	RegisterCompany(context.Context, *CompanyRequest) (*BasicResponse, error)
	RegisterEmployee(context.Context, *EmployeeRequest) (*BasicResponse, error)
	CreateNewDepartment(context.Context, *DepartmentRequest) (*BasicResponse, error)
	EmployPerson(context.Context, *EmploymentRequest) (*BasicResponse, error)
}

// UnimplementedEmploymentCenterServer should be embedded to have forward compatible implementations.
type UnimplementedEmploymentCenterServer struct {
}

func (UnimplementedEmploymentCenterServer) RegisterCompany(context.Context, *CompanyRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCompany not implemented")
}
func (UnimplementedEmploymentCenterServer) RegisterEmployee(context.Context, *EmployeeRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEmployee not implemented")
}
func (UnimplementedEmploymentCenterServer) CreateNewDepartment(context.Context, *DepartmentRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewDepartment not implemented")
}
func (UnimplementedEmploymentCenterServer) EmployPerson(context.Context, *EmploymentRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmployPerson not implemented")
}

// UnsafeEmploymentCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmploymentCenterServer will
// result in compilation errors.
type UnsafeEmploymentCenterServer interface {
	mustEmbedUnimplementedEmploymentCenterServer()
}

func RegisterEmploymentCenterServer(s grpc.ServiceRegistrar, srv EmploymentCenterServer) {
	s.RegisterService(&EmploymentCenter_ServiceDesc, srv)
}

func _EmploymentCenter_RegisterCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmploymentCenterServer).RegisterCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmploymentCenter/RegisterCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmploymentCenterServer).RegisterCompany(ctx, req.(*CompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmploymentCenter_RegisterEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmploymentCenterServer).RegisterEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmploymentCenter/RegisterEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmploymentCenterServer).RegisterEmployee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmploymentCenter_CreateNewDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmploymentCenterServer).CreateNewDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmploymentCenter/CreateNewDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmploymentCenterServer).CreateNewDepartment(ctx, req.(*DepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmploymentCenter_EmployPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmploymentCenterServer).EmployPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmploymentCenter/EmployPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmploymentCenterServer).EmployPerson(ctx, req.(*EmploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmploymentCenter_ServiceDesc is the grpc.ServiceDesc for EmploymentCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmploymentCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EmploymentCenter",
	HandlerType: (*EmploymentCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCompany",
			Handler:    _EmploymentCenter_RegisterCompany_Handler,
		},
		{
			MethodName: "RegisterEmployee",
			Handler:    _EmploymentCenter_RegisterEmployee_Handler,
		},
		{
			MethodName: "CreateNewDepartment",
			Handler:    _EmploymentCenter_CreateNewDepartment_Handler,
		},
		{
			MethodName: "EmployPerson",
			Handler:    _EmploymentCenter_EmployPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
